version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Load from .env file
    volumes:
      - .:/app
    command: gunicorn -w 4 -b 0.0.0.0:5000 server:app
