name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Log in to GitHub Container Registry (if needed)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Svelte image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            twangodev/uw-coursemap/svelte:latest
            ${{ github.event_name == 'release' && 'twangodev/uw-coursemap/svelte:' + github.event.release.tag_name || '' }}

      - name: Build and push Search image
        uses: docker/build-push-action@v6
        with:
          context: ./search
          file: Dockerfile
          push: true
          tags: |
            wangodev/uw-coursemap/search:latest
            ${{ github.event_name == 'release' && 'twangodev/uw-coursemap/search:' + github.event.release.tag_name || '' }}