name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine Tag
        id: set_tag
        run: |
          set -e
          if [[ "${GITHUB_EVENT_NAME}" == "release" ]]; then
            # Remove the 'refs/tags/' prefix to get just the tag name.
            tag="${GITHUB_REF#refs/tags/}"
          else
            tag="${GITHUB_SHA}"
          fi
          echo "TAG=${tag}" >> "${GITHUB_OUTPUT}"
          echo "Using tag: ${tag}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Svelte image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            twango/uw-coursemap-web:latest
            twango/uw-coursemap-web:${{ steps.set_tag.outputs.TAG }}
            ghcr.io/twangodev/uw-coursemap-web:latest
            ghcr.io/twangodev/uw-coursemap-web:${{ steps.set_tag.outputs.TAG }}

      - name: Build and push Search image
        uses: docker/build-push-action@v6
        with:
          context: ./search
          file: Dockerfile
          push: true
          tags: |
            twango/uw-coursemap-search:latest
            twango/uw-coursemap-search:${{ steps.set_tag.outputs.TAG }}
            ghcr.io/twangodev/uw-coursemap-search:latest
            ghcr.io/twangodev/uw-coursemap-search:${{ steps.set_tag.outputs.TAG }}